print "1..22 color,backColor,fillPattern,lineEnd,lineWidth,linePattern,rop,rop2,transform,textOpaque,textOutBaseline,color,backColor,fillPattern,lineEnd,lineWidth,linePattern,rop,rop2,transform,textOpaque,textOutBaseline";

my $a = Prima::Drawable-> create( width => 1, height => 1, type => im::RGB);
$a-> color( 0x123456);
ok( $a-> color == 0x123456);
$a-> backColor( 0x654321);
ok( $a-> backColor == 0x654321);
$a-> fillPattern( [0..7]); my $i = 0;
ok( 0 == scalar grep { $i++ != $_ } @{$a-> fillPattern});
$a-> lineEnd( le::Round);
ok( $a-> lineEnd == le::Round);
$a-> lineWidth( 5);
ok( $a-> lineWidth == 5);
$a-> linePattern( lp::Dash);
ok( $a-> linePattern eq lp::Dash);
$a-> rop( rop::NotSrcXor);
ok( $a-> rop == rop::NotSrcXor);
$a-> rop2( rop::NotSrcXor);
ok( $a-> rop2 == rop::NotSrcXor);
$a-> transform( 1, 2);
my @z = $a-> transform;
ok( $z[0] == 1 && $z[1] == 2);
$a-> textOpaque( 1);
ok( $a-> textOpaque == 1);
$a-> textOutBaseline( 1);
ok( $a-> textOutBaseline == 1);
$a-> begin_paint;
$a-> end_paint;
ok( $a-> color == 0x123456);
ok( $a-> backColor == 0x654321);
$i = 0;
ok( 0 == scalar grep { $i++ != $_ } @{$a-> fillPattern});
ok( $a-> lineEnd == le::Round);
ok( $a-> lineWidth == 5);
ok( $a-> linePattern eq lp::Dash);
ok( $a-> rop == rop::NotSrcXor);
ok( $a-> rop2 == rop::NotSrcXor);
@z = $a-> transform;
ok( $z[0] == 1 && $z[1] == 2);
ok( $a-> textOpaque == 1);
ok( $a-> textOutBaseline == 1);

1;
