package Prima::FileDialog;
use base qw(Prima::Dialog::FileDialog);
package Prima::OpenDialog;
use base qw(Prima::Dialog::OpenDialog);
package Prima::SaveDialog;
use base qw(Prima::Dialog::SaveDialog);
package Prima::ChDirDialog;
use base qw(Prima::Dialog::ChDirDialog);
warn("Warning: Prima::FileDialog is deprecated. Use Prima::Dialog::FileDialog instead\n");
1;
