#! /usr/bin/perl
use strict;
use warnings;
use Test::More;

eval 'use Test::Pod::Coverage';
plan skip_all => 'Test::Pod::Coverage required for testing POD coverage'
     if $@;
plan tests => 57;

pod_coverage_ok('Prima::Buttons');
pod_coverage_ok('Prima::Calendar');
pod_coverage_ok('Prima::ColorDialog');
pod_coverage_ok('Prima::ComboBox');
pod_coverage_ok('Prima::DetailedList');
pod_coverage_ok('Prima::DetailedOutline');
pod_coverage_ok('Prima::DockManager');
pod_coverage_ok('Prima::Docks');
pod_coverage_ok('Prima::Edit');
pod_coverage_ok('Prima::EditDialog');
pod_coverage_ok('Prima::EventHook');
pod_coverage_ok('Prima::ExtLists');
pod_coverage_ok('Prima::FileDialog');
pod_coverage_ok('Prima::FontDialog');
pod_coverage_ok('Prima::FrameSet');
pod_coverage_ok('Prima::FrameSet');
pod_coverage_ok('Prima::Grids');
pod_coverage_ok('Prima::Header');
pod_coverage_ok('Prima::HelpViewer');
pod_coverage_ok('Prima::ImageDialog');
pod_coverage_ok('Prima::ImageViewer');
pod_coverage_ok('Prima::IniFile', { trustme => [ qr/^(canonicalize_fname)$/x ] });
pod_coverage_ok('Prima::InputLine');
pod_coverage_ok('Prima::IntUtils');
pod_coverage_ok('Prima::KeySelector');
pod_coverage_ok('Prima::Label');
pod_coverage_ok('Prima::Lists');
pod_coverage_ok('Prima::MDI');
pod_coverage_ok('Prima::MsgBox');
pod_coverage_ok('Prima::Notebooks');
pod_coverage_ok('Prima::noX11');
pod_coverage_ok('Prima::Outlines');
pod_coverage_ok('Prima::PodView');
pod_coverage_ok('Prima::PrintDialog');
pod_coverage_ok('Prima::RubberBand');
pod_coverage_ok('Prima::ScrollBar');
pod_coverage_ok('Prima::ScrollWidget');
pod_coverage_ok('Prima::Sliders');
pod_coverage_ok('Prima::StdBitmap');
pod_coverage_ok('Prima::StdDlg');
pod_coverage_ok('Prima::Stress');
pod_coverage_ok('Prima::Test');
pod_coverage_ok('Prima::TextView');
pod_coverage_ok('Prima::Themes');
pod_coverage_ok('Prima::Tie');
pod_coverage_ok('Prima::Utils');
pod_coverage_ok('Prima::Widgets');
pod_coverage_ok('Prima::sys::win32::FileDialog');
pod_coverage_ok('Prima::VB::CfgMaint');
pod_coverage_ok('Prima::VB::Classes');
pod_coverage_ok('Prima::VB::VBLoader');
pod_coverage_ok('Prima::PS::Encodings');
pod_coverage_ok('Prima::PS::Printer');
pod_coverage_ok('Prima::PS::Fonts');
pod_coverage_ok('Prima::PS::Drawable');
pod_coverage_ok('Prima::Image::AnimateGIF');
pod_coverage_ok('Prima::Image::TransparencyControl');
